<?xml version="1.0" encoding="utf-8"?><Database Name="InstantHelpDatabase" Class="LinqToSqlInstantHelpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\InstantHelpDatabase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Instant_Help.Properties.Settings" SettingsPropertyName="InstantHelpDatabaseConnectionString1" Provider="System.Data.SqlClient" />
</Database>